### PR TITLE
Use AWS spot requests for further savings

### PR DESCRIPTION
**Pull request by tmlgcq**
Updated main.tf to leverage cheaper spot requests and also output private IP of new instance

### CODE REVIEW

**Comment by tmlgcq** [comment]
@nicjansma - is this something you're interested in merging or should I just release these changes on my fork?

**Comment by nicjansma** [comment]
Sorry for the delay!

This one I'm not sure about, mostly because I personally deploy long-running instances.  Is it easy to make optional?

**Comment by tmlgcq** [comment]
No worries.  I also deploy instances that stay up for months or years and only once did I run into an issue with spot instances and that's because I got too aggressive with pricing.  Either way, I suppose it wouldn't be too hard to modify the code to handle it as an option.  I'll take a look this weekend and see what I can come up with.

**Comment by tmlgcq** [comment]
I think the only clean way to handle it is to modularize the aws provider and create a spot & non-spot module which can be commented out in main.tf.   "Shouldn't be too onerous."

**Pull request closed without merging**
